--Indexador
INSERT INTO Indexador VALUES('SELIC', 0.15);
INSERT INTO Indexador VALUES('SOFR', 0.0367);
INSERT INTO Indexador VALUES('TONAR', 0.00728);
--Bolsa
INSERT INTO Bolsa VALUES('B3', 'BRL', '.SA');
INSERT INTO Bolsa VALUES('NASDAQ', 'USD', '');
INSERT INTO Bolsa VALUES('NYSE', 'USD', '');
INSERT INTO Bolsa VALUES('TSE', 'JPY', '.T');
--Ticker
----B3
INSERT INTO Ticker VALUES('B3', 'PETR4');
INSERT INTO Ticker VALUES('B3', 'ITUB4');
INSERT INTO Ticker VALUES('B3', 'VALE3');
INSERT INTO Ticker VALUES('B3', 'BPAC11');
INSERT INTO Ticker VALUES('B3', 'WEGE3');
----NASDAQ
INSERT INTO Ticker VALUES('NASDAQ', 'AAPL');
INSERT INTO Ticker VALUES('NASDAQ', 'MSFT');
INSERT INTO Ticker VALUES('NASDAQ', 'NVDA');
INSERT INTO Ticker VALUES('NASDAQ', 'AMZN');
INSERT INTO Ticker VALUES('NASDAQ', 'GOOG');
----NYSE
INSERT INTO Ticker VALUES('NYSE', 'BRK-B');
INSERT INTO Ticker VALUES('NYSE', 'V');
INSERT INTO Ticker VALUES('NYSE', 'JPM');
INSERT INTO Ticker VALUES('NYSE', 'WMT');
INSERT INTO Ticker VALUES('NYSE', 'JNJ');
----TSE
INSERT INTO Ticker VALUES('TSE', '7203');
INSERT INTO Ticker VALUES('TSE', '8306');
INSERT INTO Ticker VALUES('TSE', '6758');
INSERT INTO Ticker VALUES('TSE', '6501');
INSERT INTO Ticker VALUES('TSE', '7974');
--Contrato
INSERT INTO Contrato VALUES(
NULL, 'SELIC', 500.00, DEFAULT, 3, 0.01);
INSERT INTO Contrato VALUES(
NULL, 'NYSE', 800.00, 01012026, 6, 0.012);
INSERT INTO Contrato VALUES(
NULL, 'TSE', 1000.00, 01012025, 12, 0.014);
--Acao
INSERT INTO Acao VALUES(1, 'B3', 'PETR4', 12, 500.00);
INSERT INTO Acao VALUES(2, 'NYSE', 'JNJ', 20, 800.00);
INSERT INTO Acao VALUES(3, 'TSE', '7203', 10, 500.00);
INSERT INTO Acao VALUES(3, 'TSE', '8306', 10, 500.00);